# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Position',
            new_name='Courses',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='position',
            new_name='course',
        ),
    ]
