# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-22 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_auto_20210622_1948'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
    ]
