# Generated by Django 3.2.4 on 2021-06-23 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0004_api_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Api_count',
            new_name='ApiCount',
        ),
    ]
