# Generated by Django 3.2.4 on 2021-06-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0005_rename_api_count_apicount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicount',
            name='api_count',
            field=models.IntegerField(default=0),
        ),
    ]
