# Generated by Django 3.2.4 on 2021-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0006_alter_apicount_api_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicount',
            name='api_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
