# Generated by Django 3.2.4 on 2021-06-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0007_apicount_api_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicount',
            name='api_count',
        ),
    ]
